/*
 * This source file was generated by the Gradle 'init' task
 */
package application;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DataLensTest {
    @Test void appHasAGreeting() {
        DataLens classUnderTest = new DataLens();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
