/*
 * This source file was generated by the Gradle 'init' task
 */
package application;

public class DataLens {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new DataLens().getGreeting());
    }
}
